/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Controlador.CategoriaControlador;
import Modelo.Categoria;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexa
 */
public class VistaCategoria extends javax.swing.JPanel {

    private final CategoriaControlador categoriaControlador;
    private Integer idCategoriaSeleccionada;

    /**
     * Creates new form VistaCategoria
     */
    public VistaCategoria() {
        initComponents();
     this.categoriaControlador = new CategoriaControlador();
            cargarDatosTabla();
    }
    
            private void cargarDatosTabla( ) {
        // Obtener todas las categorías del controlador
        List<Categoria> categorias = categoriaControlador.obtenerTodasCategorias();

        if (categorias != null) {
        // Obtener el modelo existente de la tabla
        DefaultTableModel model = (DefaultTableModel) tablaCategorias.getModel();
        // Limpiar las filas existentes
        model.setRowCount(0);

        // Llenar las filas con los datos de las categorías
        for (Categoria cat : categorias) {
        Object[] row = {
        cat.getIdCategoria(),
        cat.getNombreCategoria( ),
        cat.getDescripcionCategoria( )
        };
        model.addRow(row);
            }
          }
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textBuscar = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCategorias = new javax.swing.JTable();
        textNombreCategoria = new javax.swing.JTextField();
        textDescripcionCategoria = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Categorias"));

        jLabel1.setText("Nombre Categoria");

        jLabel2.setText("Descripcion Categoria");

        textBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBuscarActionPerformed(evt);
            }
        });
        textBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textBuscarKeyTyped(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                accionBotonGuardar(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        tablaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Categoria", "Nombre", "Descripcion"
            }
        ));
        tablaCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCategorias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textBuscar)
                                .addGap(116, 116, 116))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(33, 33, 33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textNombreCategoria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(textDescripcionCategoria))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnGuardar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textDescripcionCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(textBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(btnEliminar)
                            .addComponent(btnActualizar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBuscarActionPerformed

    }//GEN-LAST:event_textBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String nombre = textNombreCategoria.getText();
    String descripcion = textDescripcionCategoria.getText( );

    if (!nombre. isEmpty( ) && !descripcion. isEmpty( )) {
    categoriaControlador.crearCategoria(nombre, descripcion);
    cargarDatosTabla( );
    textNombreCategoria.setText("");
    textDescripcionCategoria.setText("");
    } else {
    javax.swing. JOptionPane. showMessageDialog(this, "Por favor, llene todos los campos.", "Error", javax. swing. JOptionPane. ERROR_MESSAGE);
     }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int filaSeleccionada = tablaCategorias.getSelectedRow();
      if (filaSeleccionada != -1) {
      int idCategoria = (int) tablaCategorias.getValueAt(filaSeleccionada, 0);
      categoriaControlador.eliminarCategoria(idCategoria);
      cargarDatosTabla( );
      } else {
javax.swing. JOptionPane. showMessageDialog(this, "Selecciona una fila para eliminar.", "Error", javax.swing. JOptionPane. ERROR_MESSAGE);}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void accionBotonGuardar(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_accionBotonGuardar
        // TODO add your handling code here:
    }//GEN-LAST:event_accionBotonGuardar

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String nombre = textNombreCategoria.getText();
      String descripcion = textDescripcionCategoria.getText( );

      if (idCategoriaSeleccionada!= null && !nombre. isEmpty( ) && !descripcion. isEmpty( ) ) {

      categoriaControlador.actualizarCategoria(idCategoriaSeleccionada, nombre, descripcion);
      cargarDatosTabla( );

      textNombreCategoria.setText("");
      textDescripcionCategoria.setText("");
      idCategoriaSeleccionada= null;

      btnEliminar.setEnabled(true);
      btnGuardar.setEnabled(true);
      } else {
      javax.swing. JOptionPane. showMessageDialog(this, "Por favor, llene todos los campos. ", "Error", javax. swing. JOptionPane. ERROR_MESSAGE);
      }


    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tablaCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCategoriasMouseClicked
        if (evt.getClickCount() == 2) {

    int filaSeleccionada = tablaCategorias.getSelectedRow();

    if (filaSeleccionada != -1) {

    idCategoriaSeleccionada = (int) tablaCategorias.getValueAt(filaSeleccionada, 0);
    String nombre = (String) tablaCategorias.getValueAt(filaSeleccionada, 1);
    String descripcion = (String) tablaCategorias.getValueAt(filaSeleccionada, 2);

    textNombreCategoria.setText(nombre);
    textDescripcionCategoria.setText(descripcion);

    btnEliminar. setEnabled(false);
    btnGuardar.setEnabled(false);}
        }
    }//GEN-LAST:event_tablaCategoriasMouseClicked

    private void textBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textBuscarKeyTyped
       String textoBusqueda = textBuscar.getText().trim().toLowerCase();
          List<Categoria> categorias = categoriaControlador.obtenerTodasCategorias();

          DefaultTableModel modelo = (DefaultTableModel) tablaCategorias.getModel();
          modelo.setRowCount(0);

          if (categorias != null) {
          for (Categoria cat : categorias) {
          if (textoBusqueda. isEmpty( ) ||
          cat.getNombreCategoria().toLowerCase().contains(textoBusqueda) ||
          cat.getDescripcionCategoria().toLowerCase().contains(textoBusqueda)) {
          Object[] fila = {
          cat.getIdCategoria(),
          cat.getNombreCategoria(),
          cat.getDescripcionCategoria()
          };
          modelo.addRow(fila);
             }
          }
       }
    }//GEN-LAST:event_textBuscarKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCategorias;
    private javax.swing.JTextField textBuscar;
    private javax.swing.JTextField textDescripcionCategoria;
    private javax.swing.JTextField textNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
